In [88]:
import pandas as pd
import numpy as np

In [89]:
df = pd.read_csv("Iris.csv")
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [90]:
(df.values == "?").sum()

0

In [91]:
df = df.replace("?", np.nan)

In [92]:
(df.values == "?").sum()

0

In [93]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [94]:
df.fillna(method = 'ffill', inplace =True)

In [95]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [96]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [97]:
df['Species'] = df['Species'].replace({'Iris-setosa': 1, 'Iris-versicolor': 2, 'Iris-virginica': 3})
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        1
1              4.9           3.0            1.4           0.2        1
2              4.7           3.2            1.3           0.2        1
3              4.6           3.1            1.5           0.2        1
4              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        3
146            6.3           2.5            5.0           1.9        3
147            6.5           3.0            5.2           2.0        3
148            6.2           3.4            5.4           2.3        3
149            5.9           3.0            5.1           1.8        3

[150 rows x 5 columns]

In [98]:
(df<0).sum().sum()

0

In [99]:
df = df[df >= 0]

In [100]:
(df<0).sum().sum()

0

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [102]:
df = df.astype(float)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    float64
dtypes: float64(5)
memory usage: 6.0 KB


In [104]:
df.shape

(150, 5)

In [105]:
z_score = np.abs((df - df.mean()) / df.std())
df1 = z_score > 3
z_score

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm   Species
0         0.897674      1.028611       1.336794      1.308593  1.220656
1         1.139200      0.124540       1.336794      1.308593  1.220656
2         1.380727      0.336720       1.393470      1.308593  1.220656
3         1.501490      0.106090       1.280118      1.308593  1.220656
4         1.018437      1.259242       1.336794      1.308593  1.220656
..             ...           ...            ...           ...       ...
145       1.034539      0.124540       0.816888      1.443121  1.220656
146       0.551486      1.277692       0.703536      0.918985  1.220656
147       0.793012      0.124540       0.816888      1.050019  1.220656
148       0.430722      0.797981       0.930239      1.443121  1.220656
149       0.068433      0.124540       0.760212      0.787951  1.220656

[150 rows x 5 columns]

In [106]:
df1.sum()

SepalLengthCm    0
SepalWidthCm     1
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [107]:
df = df[~df1.any(axis=1)]

In [108]:
df.shape

(149, 5)

In [110]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [112]:
x = df.drop('Species', axis=1)
y = df['Species']

In [113]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[149 rows x 4 columns]

In [114]:
y

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
145    3.0
146    3.0
147    3.0
148    3.0
149    3.0
Name: Species, Length: 149, dtype: float64

In [115]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25,random_state=0)

In [116]:
reg = LogisticRegression()
reg.fit(xtrain,ytrain)
yregpred = reg.predict(xtest)

In [122]:
xtest.shape

(38, 4)

In [118]:
yregpred

array([3., 3., 2., 2., 1., 3., 3., 2., 2., 2., 1., 1., 2., 1., 1., 2., 3.,
       2., 1., 1., 1., 1., 2., 1., 2., 2., 2., 1., 1., 3., 1., 2., 2., 3.,
       1., 2., 3., 2.])

In [123]:
accuracy_score(ytest,yregpred)

0.8947368421052632

In [125]:
gau = GaussianNB()
gau.fit(xtrain,ytrain)
ygaupred = gau.predict(xtest)

In [127]:
xtest.shape

(38, 4)

In [128]:
ygaupred

array([2., 3., 2., 2., 1., 3., 3., 2., 2., 2., 1., 1., 2., 1., 1., 2., 3.,
       2., 1., 1., 1., 1., 2., 1., 2., 2., 2., 1., 1., 3., 1., 2., 2., 3.,
       1., 2., 3., 2.])

In [129]:
accuracy_score(ytest,ygaupred)

0.868421052631579

In [130]:
knn = KNeighborsClassifier()
knn.fit(xtrain,ytrain)
yknnpred = knn.predict(xtest)

In [131]:
xtest.shape

(38, 4)

In [132]:
yknnpred

array([3., 3., 2., 2., 1., 3., 3., 2., 2., 2., 1., 1., 2., 1., 1., 3., 3.,
       2., 1., 1., 1., 1., 2., 1., 2., 2., 2., 1., 1., 3., 1., 2., 2., 3.,
       1., 2., 3., 2.])

In [133]:
accuracy_score(ytest,yknnpred)

0.9210526315789473